///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ArticleModelArticlesSource {
/*
{
  "id": null,
  "name": "Haberturk.com"
}
*/

  String? id;
  String? name;

  ArticleModelArticlesSource({
    this.id,
    this.name,
  });
  ArticleModelArticlesSource.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ArticleModelArticles {
/*
{
  "source": {
    "id": null,
    "name": "Haberturk.com"
  },
  "author": "Habertürk",
  "title": "Teknolojide maaşlar ne kadar arttı?",
  "description": "“Teknoloji Sektörü Ücret ve Yan Haklar Raporu”na göre daha önce yılda bir kez maaşlarını gözden geçiren şirketler, artık yılda en az iki gözden geçiriyor. Hibrit modelinden tamamen uzaktan çalışma modeline yönelen teknoloji şirketleri maaşlara 2022’de sene ba…",
  "url": "https://www.haberturk.com/teknoloji-sektorunde-maaslar-ne-kadar-artti-3540529-teknoloji",
  "urlToImage": "https://im.haberturk.com/2022/11/21/ver1669018065/3540529_1200x627.jpg",
  "publishedAt": "2022-11-21T07:56:24Z",
  "content": "Endeavor Türkiye ile giriimci irketler için insan ve kültür konularnda danmanlk hizmetleri veren Melonn ortak yürüttüü Teknoloji Sektörü Ücret ve Yan Haklar Raporunun sonuçlar açkland.\r\n Türkiyenin h… [+6100 chars]"
}
*/

  ArticleModelArticlesSource? source;
  String? author;
  String? title;
  String? description;
  String? url;
  String? urlToImage;
  String? publishedAt;
  String? content;

  ArticleModelArticles({
    this.source,
    this.author,
    this.title,
    this.description,
    this.url,
    this.urlToImage,
    this.publishedAt,
    this.content,
  });
  ArticleModelArticles.fromJson(Map<String, dynamic> json) {
    source = (json['source'] != null) ? ArticleModelArticlesSource.fromJson(json['source']) : null;
    author = json['author']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    url = json['url']?.toString();
    urlToImage = json['urlToImage']?.toString();
    publishedAt = json['publishedAt']?.toString();
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (source != null) {
      data['source'] = source!.toJson();
    }
    data['author'] = author;
    data['title'] = title;
    data['description'] = description;
    data['url'] = url;
    data['urlToImage'] = urlToImage;
    data['publishedAt'] = publishedAt;
    data['content'] = content;
    return data;
  }
}

class ArticleModel {
/*
{
  "status": "ok",
  "totalResults": 11,
  "articles": [
    {
      "source": {
        "id": null,
        "name": "Haberturk.com"
      },
      "author": "Habertürk",
      "title": "Teknolojide maaşlar ne kadar arttı?",
      "description": "“Teknoloji Sektörü Ücret ve Yan Haklar Raporu”na göre daha önce yılda bir kez maaşlarını gözden geçiren şirketler, artık yılda en az iki gözden geçiriyor. Hibrit modelinden tamamen uzaktan çalışma modeline yönelen teknoloji şirketleri maaşlara 2022’de sene ba…",
      "url": "https://www.haberturk.com/teknoloji-sektorunde-maaslar-ne-kadar-artti-3540529-teknoloji",
      "urlToImage": "https://im.haberturk.com/2022/11/21/ver1669018065/3540529_1200x627.jpg",
      "publishedAt": "2022-11-21T07:56:24Z",
      "content": "Endeavor Türkiye ile giriimci irketler için insan ve kültür konularnda danmanlk hizmetleri veren Melonn ortak yürüttüü Teknoloji Sektörü Ücret ve Yan Haklar Raporunun sonuçlar açkland.\r\n Türkiyenin h… [+6100 chars]"
    }
  ]
}
*/

  String? status;
  int? totalResults;
  List<ArticleModelArticles?>? articles;

  ArticleModel({
    this.status,
    this.totalResults,
    this.articles,
  });
  ArticleModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    totalResults = json['totalResults']?.toInt();
    if (json['articles'] != null) {
      final v = json['articles'];
      final arr0 = <ArticleModelArticles>[];
      v.forEach((v) {
        arr0.add(ArticleModelArticles.fromJson(v));
      });
      articles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['totalResults'] = totalResults;
    if (articles != null) {
      final v = articles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['articles'] = arr0;
    }
    return data;
  }
}
